# Generated by Django 4.1.7 on 2023-04-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vkuser',
            name='namefull',
        ),
    ]
